// Interface automatically generated by schemas-to-ts

export interface Character {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: string;
    imageUrl?: string;
    health?: number;
    mana?: number;
  };
}
export interface Character_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  imageUrl?: string;
  health?: number;
  mana?: number;
}

export interface Character_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  imageUrl?: string;
  health?: number;
  mana?: number;
}

export interface Character_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  imageUrl?: string;
  health?: number;
  mana?: number;
}
