// Interface automatically generated by schemas-to-ts

export interface Damaging {
  dmgAmount?: number;
  ignoresInvulnerability?: boolean;
}
export interface Damaging_Plain {
  dmgAmount?: number;
  ignoresInvulnerability?: boolean;
}

export interface Damaging_NoRelations {
  dmgAmount?: number;
  ignoresInvulnerability?: boolean;
}

