// Interface automatically generated by schemas-to-ts

export interface Healing {
  healAmount?: number;
}
export interface Healing_Plain {
  healAmount?: number;
}

export interface Healing_NoRelations {
  healAmount?: number;
}

