// Interface automatically generated by schemas-to-ts

export interface Skill {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: string;
    imageUrl?: string;
    cooldown?: number;
    manaCost?: number;
  };
}
export interface Skill_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
}

export interface Skill_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
}

export interface Skill_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
}
