// Interface automatically generated by schemas-to-ts

import { Mechanic } from '../../../../components/mechanic/interfaces/Mechanic';
import { Mechanic_Plain } from '../../../../components/mechanic/interfaces/Mechanic';
import { Mechanic_NoRelations } from '../../../../components/mechanic/interfaces/Mechanic';

export interface Skill {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: string;
    imageUrl?: string;
    cooldown?: number;
    manaCost?: number;
    mechanic: Mechanic[];
  };
}
export interface Skill_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
  mechanic: Mechanic_Plain[];
}

export interface Skill_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
  mechanic: Mechanic_NoRelations[];
}

export interface Skill_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageUrl?: string;
  cooldown?: number;
  manaCost?: number;
  mechanic: Mechanic_Plain[];
}
